"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SkillOptService = void 0;
const skillRegistry_1 = require("./skillRegistry");
const trajectoryRecorder_1 = require("./trajectoryRecorder");
const evaluator_1 = require("./evaluator");
const reflectionEngine_1 = require("./reflectionEngine");
const candidateGenerator_1 = require("./candidateGenerator");
const validationGate_1 = require("./validationGate");
const logger_1 = require("../../utils/logger");
class SkillOptService {
    static instance;
    registry;
    recorder;
    reflection;
    generator;
    validationGate;
    logger = logger_1.Logger.getInstance();
    constructor(workspaceRoot) {
        this.registry = skillRegistry_1.SkillRegistry.getInstance(workspaceRoot);
        this.recorder = trajectoryRecorder_1.TrajectoryRecorder.getInstance(workspaceRoot);
        this.reflection = reflectionEngine_1.ReflectionEngine.getInstance();
        this.generator = candidateGenerator_1.CandidateGenerator.getInstance();
        this.validationGate = validationGate_1.ValidationGate.getInstance();
    }
    static getInstance(workspaceRoot) {
        if (!SkillOptService.instance) {
            SkillOptService.instance = new SkillOptService(workspaceRoot);
        }
        return SkillOptService.instance;
    }
    static resetInstance() {
        SkillOptService.instance = undefined;
    }
    /**
     * Executes the complete optimization loop.
     * @param skillName The name of the skill category to optimize.
     * @param validationRunner A callback that runs benchmark tests on the new candidate content and returns its score.
     */
    async optimize(skillName, validationRunner) {
        // 1. Load current best skill
        const bestSkill = this.registry.getBestSkill(skillName);
        if (!bestSkill) {
            throw new Error(`Skill ${skillName} not found or has no best version.`);
        }
        // 2. Load historical trajectories
        const allTrajectories = this.recorder.getTrajectories();
        const skillTrajectories = allTrajectories.filter(t => t.skill === skillName && t.skillVersion === bestSkill.metadata.version);
        if (skillTrajectories.length === 0) {
            throw new Error(`No trajectories found for skill ${skillName} (version ${bestSkill.metadata.version}).`);
        }
        // 3. Evaluate relevant trajectories to get baseline score
        const evaluator = evaluator_1.EvaluatorFactory.getEvaluator();
        let totalScore = 0;
        for (const t of skillTrajectories) {
            totalScore += evaluator.evaluate(t).score;
        }
        const scoreBefore = totalScore / skillTrajectories.length;
        // 4. Ask ReflectionEngine for repeated problems
        const reflectionResult = await this.reflection.reflect(skillTrajectories);
        if (reflectionResult.improvements.length === 0) {
            throw new Error('Optimization halted: No behavioral improvements proposed by reflection.');
        }
        // 5. Generate candidate skill
        const candidateResult = await this.generator.generateCandidate(bestSkill.content, reflectionResult);
        if (candidateResult.edits.length === 0) {
            throw new Error('Optimization halted: No edits generated for the candidate.');
        }
        // Save candidate to registry as draft
        const candidateSkill = this.registry.createSkillVersion(skillName, candidateResult.candidateContent, bestSkill.metadata.version, 'Candidate generated by SkillOpt');
        candidateSkill.metadata.status = 'draft';
        this.registry.saveSkillVersion(skillName, candidateSkill);
        // 6. Validate candidate
        this.logger.log(`Validating candidate v${candidateSkill.metadata.version} for ${skillName}...`);
        const scoreAfter = await validationRunner(candidateResult.candidateContent);
        // 7 & 8. Validation Gate (Accept or Reject)
        const decision = this.validationGate.evaluateDecision(scoreBefore, scoreAfter, 0.02);
        if (decision.decision === 'accepted') {
            // Promote candidate
            this.registry.promoteSkill(skillName, candidateSkill.metadata.version);
            this.logger.log(`Optimization ACCEPTED: Promoted ${skillName} to v${candidateSkill.metadata.version}`);
        }
        else {
            // Reject candidate
            candidateSkill.metadata.status = 'archived';
            candidateSkill.metadata.changeDescription = `Rejected: ${decision.reason}`;
            this.registry.saveSkillVersion(skillName, candidateSkill);
            this.logger.log(`Optimization REJECTED: Candidate v${candidateSkill.metadata.version} discarded.`);
        }
        // 9. Return Optimization Report
        return {
            skill: skillName,
            previousVersion: bestSkill.metadata.version,
            candidateVersion: candidateSkill.metadata.version,
            scoreBefore: scoreBefore,
            scoreAfter: scoreAfter,
            improvement: decision.improvement,
            decision: decision.decision,
            changes: candidateResult.edits,
            reason: decision.reason
        };
    }
}
exports.SkillOptService = SkillOptService;
//# sourceMappingURL=skillOptService.js.map