import { expect } from 'chai';
import * as fs from 'fs';
import * as path from 'path';
import { SkillRegistry } from './skillRegistry';
import { BuiltInSkillSeeder } from './builtInSkillSeeder';

describe('SkillOps Built-in Skill Lifecycle', () => {
  let registry: SkillRegistry;
  const testWorkspace = path.join(__dirname, '.test_agents');

  beforeEach(() => {
    if (fs.existsSync(testWorkspace)) {
      fs.rmSync(testWorkspace, { recursive: true, force: true });
    }
    fs.mkdirSync(testWorkspace, { recursive: true });
    SkillRegistry.resetInstance();
    registry = SkillRegistry.getInstance(testWorkspace);
  });

  afterEach(() => {
    if (fs.existsSync(testWorkspace)) {
      fs.rmSync(testWorkspace, { recursive: true, force: true });
    }
    SkillRegistry.resetInstance();
  });

  it('1. Built-in skill creation', () => {
    BuiltInSkillSeeder.seedSkills(registry);
    const skills = registry.listSkills();
    expect(skills.length).to.be.greaterThan(0);
    const reactMeta = registry.getSkillCategoryMetadata('react');
    expect(reactMeta).to.not.be.null;
    expect(reactMeta?.builtIn).to.be.true;
    expect(reactMeta?.userModified).to.be.false;
  });

  it('2. Built-in skill editing & 3. User version preservation', () => {
    BuiltInSkillSeeder.seedSkills(registry);
    
    // Simulate user edit
    const newVersion = registry.createSkillVersion('react', 'User modified react skill content', registry.getSkillCategoryMetadata('react')?.bestVersion, 'User edit');
    registry.saveSkillVersion('react', newVersion);
    registry.updateSkillCategoryMetadata('react', { userModified: true, sourceVersion: 'user' });
    registry.promoteSkill('react', newVersion.metadata.version);
    
    // Simulate extension update/restart
    BuiltInSkillSeeder.seedSkills(registry); 

    const reactMeta = registry.getSkillCategoryMetadata('react');
    expect(reactMeta?.userModified).to.be.true;
    expect(reactMeta?.bestVersion).to.equal(2);
    
    const content = registry.loadSkillContent('react', 2);
    expect(content).to.equal('User modified react skill content');
  });

  it('4. Built-in skill deletion & 5. Deleted built-in skill not recreated on restart', () => {
    BuiltInSkillSeeder.seedSkills(registry);
    registry.softDeleteSkill('react');
    
    // Simulate extension update/restart
    BuiltInSkillSeeder.seedSkills(registry); 

    const reactMeta = registry.getSkillCategoryMetadata('react');
    expect(reactMeta?.userDeleted).to.be.true;
  });

  it('6. Built-in skill restoration', async () => {
    BuiltInSkillSeeder.seedSkills(registry);
    
    const newVersion = registry.createSkillVersion('react', 'User modified react skill content', registry.getSkillCategoryMetadata('react')?.bestVersion, 'User edit');
    registry.saveSkillVersion('react', newVersion);
    registry.updateSkillCategoryMetadata('react', { userModified: true });
    registry.promoteSkill('react', newVersion.metadata.version);
    
    const originalContent = BuiltInSkillSeeder.getBuiltInContent('react') || '';
    registry.restoreBuiltInSkill('react', originalContent);
    
    const reactMeta = registry.getSkillCategoryMetadata('react');
    expect(reactMeta?.userModified).to.be.false;
    expect(reactMeta?.bestVersion).to.equal(3); // 1: built-in, 2: user edit, 3: restored
  });

  it('7. Version history & 8. Rollback', () => {
    BuiltInSkillSeeder.seedSkills(registry);
    
    const newVersion = registry.createSkillVersion('react', 'User modified react skill content', registry.getSkillCategoryMetadata('react')?.bestVersion, 'User edit');
    registry.saveSkillVersion('react', newVersion);
    registry.updateSkillCategoryMetadata('react', { userModified: true });
    registry.promoteSkill('react', newVersion.metadata.version);
    
    registry.rollbackSkill('react', 1);
    
    const reactMeta = registry.getSkillCategoryMetadata('react');
    expect(reactMeta?.bestVersion).to.equal(1);
  });

  it('9. Optimization candidate creation', () => {
    BuiltInSkillSeeder.seedSkills(registry);
    
    const newVersion = registry.createSkillVersion('react', 'Optimized content', registry.getSkillCategoryMetadata('react')?.bestVersion, 'Candidate generated by SkillOpt');
    registry.saveSkillVersion('react', newVersion);
    registry.updateSkillCategoryMetadata('react', { userModified: true });
    registry.promoteSkill('react', newVersion.metadata.version);
    
    const reactMeta = registry.getSkillCategoryMetadata('react');
    expect(reactMeta?.bestVersion).to.equal(2);
    expect(reactMeta?.userModified).to.be.true;
  });

  it('10. Extension update with user-modified skill', () => {
    BuiltInSkillSeeder.seedSkills(registry);
    
    const newVersion = registry.createSkillVersion('react', 'User modified react skill content', registry.getSkillCategoryMetadata('react')?.bestVersion, 'User edit');
    registry.saveSkillVersion('react', newVersion);
    registry.updateSkillCategoryMetadata('react', { userModified: true });
    registry.promoteSkill('react', newVersion.metadata.version);
    
    // Seeder should not overwrite user version
    BuiltInSkillSeeder.seedSkills(registry); 
    
    const reactMeta = registry.getSkillCategoryMetadata('react');
    expect(reactMeta?.bestVersion).to.equal(2);
    expect(reactMeta?.userModified).to.be.true;
  });

  it('11. Extension update with unmodified skill & 12. Duplicate prevention', () => {
    BuiltInSkillSeeder.seedSkills(registry);
    const initialSkills = registry.listSkills();
    
    BuiltInSkillSeeder.seedSkills(registry); // run again
    
    const skills = registry.listSkills();
    expect(skills.length).to.equal(initialSkills.length); // no duplicates
    const reactMeta = registry.getSkillCategoryMetadata('react');
    expect(reactMeta?.bestVersion).to.equal(1); // no new versions if content is same
  });
});
