import { TaskArtifact, RequirementStatus } from './types';
import { Logger } from '../../utils/logger';
import * as fs from 'fs/promises';
import * as path from 'path';

export interface CoverageResult {
    allSatisfied: boolean;
    criticalUnverified: number;
    report: string;
    canComplete: boolean;
}

export class RequirementCoverageAnalyzer {
    private readonly logger = Logger.getInstance();

    public analyze(artifact: TaskArtifact): CoverageResult {
        this.logger.log(`[RequirementCoverageAnalyzer] Analyzing coverage for ${artifact.taskId}`);
        
        let allSatisfied = true;
        let criticalUnverified = 0;
        let report = `## Requirement Coverage Report — ${artifact.taskId}\n\n`;
        report += `| ID | Priority | Category | Type | Status | Description |\n`;
        report += `|----|----------|----------|------|--------|-------------|\n`;

        for (const req of artifact.requirements) {
            let symbol = '❓';
            let satisfied = true;

            if (req.status === RequirementStatus.SATISFIED) {
                symbol = '✅';
            } else if (req.status === RequirementStatus.FAILED) {
                symbol = '❌';
                satisfied = false;
            } else if (req.status === RequirementStatus.PENDING || req.status === RequirementStatus.IN_PROGRESS) {
                symbol = '⏳';
                satisfied = false;
            } else if (req.status === RequirementStatus.BLOCKED) {
                symbol = '⛔';
                satisfied = false;
            } else if (req.status === RequirementStatus.SUPERSEDED) {
                symbol = '🔄';
            }

            if (!satisfied) {
                allSatisfied = false;
                // CRITICAL and HIGH requirements gate completion
                if (req.priority === 'CRITICAL' || req.priority === 'HIGH') {
                    criticalUnverified++;
                }
            }

            report += `| ${symbol} ${req.id} | ${req.priority} | ${req.category} | ${req.type} | ${req.status} | ${req.description} |\n`;
        }

        report += `\n**Summary**: ${allSatisfied ? '✅ ALL SATISFIED' : `⚠️ ${criticalUnverified} critical requirement(s) unverified`}\n`;

        // A task can complete only if no CRITICAL/HIGH requirements are unverified
        const canComplete = criticalUnverified === 0;

        return { allSatisfied, criticalUnverified, report, canComplete };
    }

    public async generateCompletionReport(
        artifact: TaskArtifact,
        coverage: CoverageResult,
        filesChanged: string[],
        outputDir: string
    ): Promise<string> {
        const reportPath = path.join(outputDir, artifact.taskId, 'TaskCompletionReport.md');
        await fs.mkdir(path.dirname(reportPath), { recursive: true });

        let md = `# Task Completion Report\n\n`;
        md += `## Summary\n- **Task ID**: ${artifact.taskId}\n`;
        md += `- **Status**: ${artifact.state}\n`;
        md += `- **Complexity**: ${artifact.complexity}\n\n`;
        md += `## ${coverage.report}\n`;
        md += `## Files Changed\n${filesChanged.map(f => `- ${f}`).join('\n')}\n\n`;
        md += `## Known Limitations\n- Execution loop is not yet fully wired to live LLM calls — awaiting integration.\n`;
        md += `\n---\n*Generated by Chanakya AI Enhancer — Long Task Engine*\n`;

        await fs.writeFile(reportPath, md, 'utf-8');
        this.logger.log(`[RequirementCoverageAnalyzer] ✓ Completion report saved to ${reportPath}`);
        return reportPath;
    }
}

